name: ezflap_tests
description: ezFlap tester application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.9.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.1.4

  ezflap:
    path: "../ezflap"

  ezflap_widgets:
    path: "../ezflap_widgets"

  build_runner: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
